name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
categories:
  - title: "⬆️ Dependencies"
    collapse-after: 1
    labels:
      - "dependencies"
template: |
  ## What's Changed
  $CHANGES
version-resolver:
  major:
    labels:
      - 'major-release'
  minor:
    labels:
      - 'minor-release'
  patch:
    labels:
      - 'patch-release'
  default: patch
