name: Build and publish NPM package

on:
  workflow_dispatch:
    inputs:
      node_version:
        default: '20'
        description: 'Node version to use'
        required: true
        type: string

jobs:
  build-package:
    environment: release
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0 # npm run prod requires tags, sadly this is the only way to get them.
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node_version }}
          registry-url: 'https://registry.npmjs.org' # Must explicitly set this for NODE_AUTH_TOKEN to work below
      - name: Install dependencies
        run: npm ci
      - name: Test with npm
        run: npm run test
      - name: Build with npm
        run: npm run prod
      - name: Publish with npm
        if: startsWith(github.ref, 'refs/tags')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm config set git-tag-version=false
          npm version $(git describe --tags)
          npm publish --access public
